[global]
; Не демонизировать (обязательно в Docker)
daemonize = no

; Логи ошибок — в stderr контейнера
error_log = /proc/self/fd/2

[www]
; Слушать все интерфейсы на 9000 порту (для связки с Nginx)
listen = 0.0.0.0:9000

; Логи доступа — в stderr контейнера
access.log = /proc/self/fd/2

; Ошибки PHP — тоже в stderr контейнера
php_admin_value[error_log] = /proc/self/fd/2
php_admin_flag[log_errors] = on
